# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details
# used Silverstripe Translatable as a guide

language: php
php:
 - 5.6

sudo: false

env:
 - DB=MYSQL CORE_RELEASE=3.4 PDO=1

before_script:
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script:
# Execute tests
 - vendor/bin/phpunit consumer/tests/
