language: php

dist: trusty

matrix:
  include:
    - php: 7.1
      env: DB=MYSQL

before_script:
  # Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  # Install composer dependencies
  - composer validate
  - composer require --prefer-dist --no-update silverstripe/recipe-cms:^4@dev
  - composer require --no-update phpunit/phpunit:^5.7
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
 - vendor/bin/phpunit
