# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details
# used Silverstripe Translatable as a guide

language: php
php:
 - 7.1

sudo: false

env:
 - DB=MYSQL CORE_RELEASE=4.1 PDO=1

before_script:
  # Init PHP
  - composer self-update || true
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  # Install composer dependencies
  - composer validate
  - composer require --no-update silverstripe/recipe-core:^1.0
  - composer require --no-update phpunit/phpunit:^5.7
  - if [[ $DB == PGSQL ]]; then composer require silverstripe/postgresql:2.0.x-dev --prefer-dist --no-update; fi
  - if [[ $DB == SQLITE ]]; then composer require silverstripe/sqlite3:2.1.x-dev --prefer-dist --no-update; fi
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
 - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests flush=1; fi
 - if [[ $PHPCS_TEST ]]; then composer run-script lint; fi
